### ISSUE TITLE
Improving modularity in JavaScript

### ISSUE THREAD

**Issue by JDchauhan** [ankitrai96/multilingual-algorithm-vault#11]
- [x] Improving Modularity in JavaScript

There are some improvements needed in JavaScript files. The features to improve is to make them importable in a very user-friendly way so that the person can use them as a library.
#9 is the previous modular version that is needed to be improved.

**Comment by ankitrai96** [comment]
**custom sized data set**
@JDchauhan , as discussed earlier, we agreed to allow the user to enter the size of data set rather than implicitly generating one of size million. I made amendments in python modules. However, I can see you haven't. Please look into it.

```
    var data=[];
    var value;
    var n=1000000;
    var n1=1000000;
    function generateDatasets(){
        console.log("generating million data sets...");
        value=parseInt(Math.random()*1000);
        for(var i=0;i<n;i++){
            data[i]=parseInt(Math.random()*1000);
        }
```

**Comment by JDchauhan** [comment]
Yes @ankitrai96  I haven't done it yet! but I will soon update it with some other fixes...
