### ISSUE TITLE
enhancement in structure

### ISSUE THREAD

**Issue by JDchauhan** [ankitrai96/multilingual-algorithm-vault#13]
@ankitrai96 As the aim of this repository is to serve the algorithms together so i will suggest you to keep the Analyse performance files one per language to make it simple and appleaning.
i.e,  inside performanceAnalyses folder files like performanceMeasure.cpp, performanceMeasure.js, performanceMeasure.py and so on exists instead of keeping them different according to the type of algorithm.

- [x] Enhancements in **performanceAnalyses folder** to do all the performance analyzing work in single file.

**Comment by ankitrai96** [comment]
@JDchauhan as discussed earlier, while your proposal for a consolidated performanceMeasure file is good and definitely noteworthy, it remains debatable. For instance, it is not clear if putting sorting and searching algorithms under the same umbrella won't be like comparing apples and oranges. 

Either way, the current scenario is not bad. And therefore, unless there is some serious setback with it, I would appreciate if we put our efforts in learning new algorithms and building up this repository.
