### ISSUE TITLE
performanceMeasure.js missing

### ISSUE THREAD

**Issue by ankitrai96** [ankitrai96/multilingual-algorithm-vault#2]
@JDchauhan please follow a certain definite convention while naming your files and structuring your code. Take note of the following:-

- performanceMeasure is the agreed and decided name for the file that will import all the other ones in it. you've made a similar file called main.js. That's good! However, please rename it to the above mentioned
- Also, please keep in mind that the code you write should be modular enough that they can be used plain and simple while making the proposed front-end for this project of ours

Lastly, **be careful while Removing/Renaming a file in Git**
You can **NOT** simply delete/rename and commit. Rather, first you'll have to **remove it from staging area of git**  
So, for this particular issue, do this:-

1. rename main.js to performanceMeasure.js
2. in Git Bash/ Terminal type the following code to unstage your file
`git rm main.js`
3. then, to stage the new one, that is, the renamed one, type
`git add path\to\performanceMeasurement.js`
4. And finally, commit whenever you're ready!

Thank you for your contributions. Kudos to learning together!

**Comment by JDchauhan** [comment]
i acknowledge, will soon update it.
